leaflet:
  css: external/leaflet.css
  jshead: [external/leaflet.js, external/leaflet.geocsv.js]
  cdn:
    css: http://leafletjs.com/dist/leaflet.css
    jshead: 
      - http://leafletjs.com/dist/leaflet.js
      - https://rawgithub.com/joker-x/Leaflet.geoCSV/gh-pages/leaflet.geocsv-src.js
