leaflet:
  css: [external/leaflet.css, external/leaflet-rCharts.css]
  jshead: [external/leaflet.js, external/leaflet-providers.js]
  cdn:
    css: http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.css
    jshead: 
      - http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.js
      - https://rawgithub.com/leaflet-extras/leaflet-providers/gh-pages/leaflet-providers.js
